Repository precice/dealii-adapter, pull requests merged in 2021-01, with the labels that each got.

#39 including two flap case
  .gitignore
  linear_elasticity/include/parameter_handling.h
  linear_elasticity/linear_elasticity.cc
  nonlinear_elasticity/include/parameter_handling.h
  nonlinear_elasticity/nonlinear_elasticity.cc
Labels: enhancement

#47 Move initializeData out of writeInitialData
  adapter/adapter.h
Labels: bug

#44 Support Force data in linear solver
  linear_elasticity/include/parameter_handling.h
  linear_elasticity/linear_elasticity.cc
Labels: compatibility, enhancement
